f"Назва класу «{current_source_layer_name}» не відповідає структурі"
f"В назві класу «{current_source_layer_name}» наявні великі літери"
f"Замість назви класу використано псевдонім «{current_source_layer_name}», вимагається «{layer_inspections['layer_name_errors']['used_alias']}»"
f"В назві класу «{current_source_layer_name}» наявні пробіли"
f"В назві класу «{current_source_layer_name}» наявні кириличні літери"
f"Клас «{current_source_layer_name}» пошкоджено"
f"Невідповідний геометричний тип класу: «{layer_inspections['wrong_geometry_type'][0]}», вимагається «{layer_inspections['wrong_geometry_type'][1]}»"
f"Невідповідна СК шару: «{layer_inspections['wrong_layer_CRS'][0]}», очікується: «{layer_inspections['wrong_layer_CRS'][1]}»"
f"Помилки атрибутів:" 
f"Відсутні деякі атрибути класу:"
f"Атрибут: «{item}»"
f"Присутні атрибути, назва яких не відповідає структурі:"
f"Атрибут: «{item}»"
f"Назва атрибуту «{current_source_layer_name}» не відповідає структурі"
f"В назві атрибуту «{current_source_layer_name}» наявні великі літери"
f"Замість назви атрибуту використано псевдонім «{current_source_layer_name}», вимагається «{val}»"
f"В назві атрибуту «{current_source_layer_name}» є пробіли"
f"В назві атрибуту «{current_source_layer_name}» є кирилиця"
f"Типи атрибутів в класі не відповідають сруктурі:"
f"Атрибт «{field}» має тип:«{get_index(types,0)}», вимагається: «{get_index(types,1)}»"
f"В класі відсутні об'єкти"
f"Помилки в об'єктах:"
f"Об'єкт: '{current_feature_name}({current_feature_id})'"
f"Помилки в геометрії об'єкту:"
f"В об'єкті відсутня геометрія"
f"Геометрія об'єкту пуста(null)"
f"Тип геометрії об'єкту не відповідає сруктурі. Наявно '{feature_geom_error['geometry_type_wrong'][0]}', вимагається '{feature_geom_error['geometry_type_wrong'][1]}'"
f"Тип геометрії об'єкту не відповідає сруктурі."
f"Об'єкт виходить за межі екстента системи координат"
f"Об'єкт має не унікальний GUID"
f"Об'єкт: '{temp_feature_name}(id:{element[0]})', шару: '{temp_layer.name()}'"
f"Об'єкт має не заповнені обов'язкові атрибути"
f"Атрибут: '{element}'"
f"Об'єкт має атрибути з перевищенням довжини"
f"Атрибут: '{element}' має довжину {layer_inspections[0]}, а треба {layer_inspections[1]}"
f"Атрибут: '{element}' має довжину більше дозволеної структурою"
f"Об'єкт має атрибути зі значеннями що не відповідають класифікатору"
f"Атрибут: '{element}' має значення {layer_inspections[0]}"
f"Об'єкт має помилки топологіі"
f"Порушено правило топології «{topology_error}» в об'єкті '{current_feature_name}'({current_feature_id}), до об'єкту '{temp_feature_name}'({temp_feature.id()}), шару: '{current_layer_name}'"
f"Порушено правило топології «{topology_error}» в об'єкті '{current_feature_name}'({current_feature_id}), до об'єкту '{temp_feature_name}'({temp_feature.id()})"
f"Порушено правило топології «{topology_error}» в об'єкті '{current_feature_name}'({current_feature_id})